# Force nixpacks provider to ensure this file is used
providers = ["nixpacks"]

[phases.setup]
# Specify PHP 8.3 and its required extensions
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.curl",
  "php83Extensions.json",
  "php83Packages.composer",
  "nginx"
]

[phases.build]
# Define the build command
cmds = [
  "cd backend && composer install --no-dev --optimize-autoloader"
]

[start]
# Define the start command for the server
cmd = "php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf"

[variables]
PHP_VERSION = "8.3"